# Generated by Django 4.2.3 on 2023-08-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('BODYATTACK', 'BODYATTACK'), ('BODYBALANCE', 'BODYBALANCE'), ('BODYCOMBAT', 'BODYCOMBAT'), ('BODYPUMP', 'BODYPUMP'), ('BODYSTEP', 'BODYSTEP')], max_length=50)),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('BODYATTACK', 'BODYATTACK'), ('BODYBALANCE', 'BODYBALANCE'), ('BODYCOMBAT', 'BODYCOMBAT'), ('BODYPUMP', 'BODYPUMP'), ('BODYSTEP', 'BODYSTEP')], default='BODYATTACK', max_length=50),
        ),
    ]
