# Generated by Django 4.2.3 on 2023-07-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='state',
        ),
    ]
