# Generated by Django 4.2.3 on 2023-07-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_remove_registereduser_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
