# Generated by Django 4.2.3 on 2023-07-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_alter_trainer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='workout_plan_video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
